# The URL the site will be built for
base_url = "https://example.com"
title = "Someone"
# Whether to automatically compile all sass files
compile_sass = true

build_search_index = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
socials = [
    { href = "https://twitter.com/", icon = "im im-twitter", text = "Twitter" },
    { href = "https://www.linkedin.com/in/", icon = "im im-linkedin", text = "Linkedin" },
    { href = "https://github.com/", icon = "im im-github", text = "Github" },
]

menus = [
    { content = "Home", title = "home", href = "#home" },
    { content = "Blog", title = "blog", href = "/blog" },
    { content = "About", title = "sobre", href = "#sobre" },
    { content = "Experience", title = "historico", href = "#historico" },
    { content = "Some works", title = "trabalhos", href = "#trabalhos" },
]

[extra.enabled]
profile = true
about = true
menu = true
more = true
skills = true
timeline = true
projects = true
quote = true
github = true
contact = true
footer = true

[languages.pt]
generate_feed = true
build_search_index = true
